import { jsPDF } from 'jspdf';

export interface AuditFinding {
  no: number;
  name: string;
  status: 'PASS' | 'WARN' | 'FAIL' | 'ERROR' | 'INFO';
  details: string;
  context: string;
}

export interface ParsedAuditReport {
  title: string;
  target: string;
  score: number;
  grade: string;
  date: string;
  findings: AuditFinding[];
}

const TOTAL_PAGES_TOKEN = '{total_pages_count_string}';

function cleanMarkdown(value: string) {
  return value
    .replace(/\*\*/g, '')
    .replace(/\*/g, '')
    .replace(/`/g, '')
    .trim();
}

function parseKeyValue(line: string, label: string) {
  const normalized = cleanMarkdown(line);
  const prefix = `${label}:`;
  return normalized.startsWith(prefix) ? normalized.slice(prefix.length).trim() : '';
}

export function parseAuditMarkdown(title: string, target: string, content: string): ParsedAuditReport {
  const lines = content.split(/\r?\n/);
  const findings: AuditFinding[] = [];
  let current: AuditFinding | null = null;
  let parsedTarget = target;
  let score = 0;
  let grade = 'F';
  let date = new Date().toUTCString();

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    const targetValue = parseKeyValue(trimmed, 'Audit Target');
    if (targetValue) parsedTarget = targetValue;

    const dateValue = parseKeyValue(trimmed, 'Scan Timestamp');
    if (dateValue) date = dateValue;

    const scoreLine = parseKeyValue(trimmed, 'Overall Security Score');
    if (scoreLine) {
      const scoreMatch = scoreLine.match(/(\d+)\s*\/\s*100/i);
      const gradeMatch = scoreLine.match(/Grade\s*([A-F])/i);
      if (scoreMatch) score = Number(scoreMatch[1]);
      if (gradeMatch) grade = gradeMatch[1].toUpperCase();
    }

    const headingMatch = trimmed.match(/^###\s*\[(PASS|WARN|FAIL|ERROR|INFO)\]\s*(.+)$/i);
    if (headingMatch) {
      if (current) findings.push(current);
      current = {
        no: findings.length + 1,
        status: headingMatch[1].toUpperCase() as AuditFinding['status'],
        name: cleanMarkdown(headingMatch[2]),
        details: '',
        context: '',
      };
      continue;
    }

    if (!current) continue;
    const details = parseKeyValue(trimmed.replace(/^- /, '').replace(/^\* /, ''), 'Details');
    if (details) {
      current.details = details;
      continue;
    }
    const context = parseKeyValue(trimmed.replace(/^- /, '').replace(/^\* /, ''), 'Technical context');
    if (context) {
      current.context = context;
    }
  }

  if (current) findings.push(current);

  if (!findings.length) {
    findings.push({
      no: 1,
      name: 'Audit Summary',
      status: score >= 75 ? 'PASS' : score >= 55 ? 'WARN' : 'FAIL',
      details: content.slice(0, 500) || 'No detailed findings were included in this report.',
      context: 'Generated from available report text.',
    });
  }

  return {
    title,
    target: parsedTarget,
    score,
    grade,
    date,
    findings,
  };
}

function statusColors(status: AuditFinding['status']) {
  if (status === 'PASS') return { fill: [240, 253, 244], text: [22, 101, 52] };
  if (status === 'WARN') return { fill: [254, 243, 199], text: [146, 64, 14] };
  if (status === 'FAIL' || status === 'ERROR') return { fill: [254, 226, 226], text: [153, 27, 27] };
  return { fill: [241, 245, 249], text: [51, 65, 85] };
}

function gradeColor(grade: string) {
  if (grade === 'A' || grade === 'B') return [16, 185, 129];
  if (grade === 'C') return [245, 158, 11];
  return [239, 68, 68];
}

export function exportAuditToPDF(title: string, target: string, content: string) {
  const report = parseAuditMarkdown(title, target, content);
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const pageWidth = 210;
  const pageHeight = 297;
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  let currentY = 30;

  const drawHeaderFooter = () => {
    const pageNum = doc.getNumberOfPages();
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    const targetLines = doc.splitTextToSize(`CYBERKIT SECURITY REPORT | TARGET: ${report.target}`, contentWidth);
    doc.text(targetLines.slice(0, 2), margin, 12);
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.2);
    doc.line(margin, 20, pageWidth - margin, 20);

    doc.line(margin, pageHeight - 18, pageWidth - margin, pageHeight - 18);
    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(8);
    doc.text('CONFIDENTIAL - Generated by CyberKit Toolkit', margin, pageHeight - 12);
    doc.text(`Page ${pageNum} of ${TOTAL_PAGES_TOKEN}`, pageWidth - margin, pageHeight - 12, { align: 'right' });
  };

  const addContentPage = () => {
    doc.addPage();
    doc.setFillColor(255, 255, 255);
    doc.rect(0, 0, pageWidth, pageHeight, 'F');
    currentY = 30;
    drawHeaderFooter();
  };

  const ensureSpace = (height: number) => {
    if (currentY + height > pageHeight - 26) addContentPage();
  };

  doc.setFillColor(10, 14, 26);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');
  doc.setDrawColor(24, 30, 48);
  doc.setLineWidth(0.4);
  for (let x = 10; x < pageWidth; x += 30) doc.line(x, 0, x, pageHeight);
  for (let y = 10; y < pageHeight; y += 40) doc.line(0, y, pageWidth, y);

  doc.setDrawColor(34, 211, 238);
  doc.setLineWidth(1);
  doc.rect(10, 10, pageWidth - 20, pageHeight - 20);

  doc.setTextColor(34, 211, 238);
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(26);
  doc.text('CYBERKIT', margin, 40);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text('SECURITY AUDIT REPORT', margin, 50);
  doc.setDrawColor(34, 211, 238);
  doc.line(margin, 58, pageWidth - margin, 58);

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(156, 163, 175);
  doc.text('AUDIT TARGET', margin, 74);
  doc.setTextColor(255, 255, 255);
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(12);
  doc.text(doc.splitTextToSize(report.target, contentWidth), margin, 83);

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(156, 163, 175);
  doc.text('GENERATED AT', margin, 108);
  doc.setTextColor(255, 255, 255);
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(10);
  doc.text(doc.splitTextToSize(report.date, contentWidth), margin, 116);

  const color = gradeColor(report.grade);
  const circleX = pageWidth / 2;
  const circleY = 168;
  doc.setDrawColor(30, 41, 59);
  doc.setLineWidth(4);
  doc.setFillColor(15, 23, 42);
  doc.circle(circleX, circleY, 32, 'FD');
  doc.setDrawColor(color[0], color[1], color[2]);
  doc.circle(circleX, circleY, 32, 'D');
  doc.setTextColor(255, 255, 255);
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(34);
  doc.text(String(report.score), circleX, circleY + 5, { align: 'center' });
  doc.setFontSize(9);
  doc.setTextColor(156, 163, 175);
  doc.text('SCORE / 100', circleX, circleY + 14, { align: 'center' });
  doc.setFillColor(color[0], color[1], color[2]);
  doc.rect(circleX - 12, circleY + 24, 24, 10, 'F');
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.text(`GRADE ${report.grade}`, circleX, circleY + 30, { align: 'center' });

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('CONFIDENTIAL - Generated by CyberKit Toolkit', circleX, 262, { align: 'center' });

  addContentPage();
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text('1. Findings Checklist', margin, currentY);
  currentY += 8;

  const colWidths = [12, 54, 24, 80];
  const colX = [
    margin,
    margin + colWidths[0],
    margin + colWidths[0] + colWidths[1],
    margin + colWidths[0] + colWidths[1] + colWidths[2],
  ];

  const drawTableHeader = () => {
    ensureSpace(10);
    doc.setFillColor(15, 23, 42);
    doc.rect(margin, currentY, contentWidth, 8, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(8);
    doc.text('No', colX[0] + 2, currentY + 5);
    doc.text('Security Check', colX[1] + 2, currentY + 5);
    doc.text('Status', colX[2] + 2, currentY + 5);
    doc.text('Finding Details', colX[3] + 2, currentY + 5);
    currentY += 8;
  };

  drawTableHeader();

  for (const finding of report.findings) {
    const detail = finding.details || finding.context || 'Verification completed.';
    const nameLines = doc.splitTextToSize(finding.name, colWidths[1] - 4);
    const detailLines = doc.splitTextToSize(detail, colWidths[3] - 4);
    const rowHeight = Math.max(8, Math.max(nameLines.length, detailLines.length) * 4 + 4);
    ensureSpace(rowHeight + 2);
    if (currentY === 30) drawTableHeader();

    const colors = statusColors(finding.status);
    doc.setFillColor(colors.fill[0], colors.fill[1], colors.fill[2]);
    doc.rect(margin, currentY, contentWidth, rowHeight, 'F');
    doc.setDrawColor(226, 232, 240);
    doc.rect(margin, currentY, contentWidth, rowHeight, 'D');

    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(15, 23, 42);
    doc.text(String(finding.no), colX[0] + 2, currentY + 5);
    doc.text(nameLines, colX[1] + 2, currentY + 5);
    doc.setFont('Helvetica', 'bold');
    doc.setTextColor(colors.text[0], colors.text[1], colors.text[2]);
    doc.text(finding.status, colX[2] + 2, currentY + 5);
    doc.setFont('Helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    doc.text(detailLines, colX[3] + 2, currentY + 5);
    currentY += rowHeight;
  }

  currentY += 10;
  ensureSpace(12);
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text('2. Technical Context', margin, currentY);
  currentY += 8;

  for (const finding of report.findings) {
    const colors = statusColors(finding.status);
    const body = finding.context || finding.details || 'No additional context provided.';
    const wrapped = doc.splitTextToSize(body, contentWidth - 8);
    const blockHeight = 10 + wrapped.length * 4;
    ensureSpace(blockHeight);

    doc.setFillColor(colors.text[0], colors.text[1], colors.text[2]);
    doc.rect(margin, currentY, 3, 4, 'F');
    doc.setTextColor(15, 23, 42);
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(10);
    doc.text(doc.splitTextToSize(`${finding.name} (${finding.status})`, contentWidth - 8), margin + 6, currentY + 3.5);
    currentY += 7;
    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(71, 85, 105);
    doc.text(wrapped, margin + 6, currentY);
    currentY += wrapped.length * 4 + 6;
  }

  if (typeof doc.putTotalPages === 'function') {
    doc.putTotalPages(TOTAL_PAGES_TOKEN);
  }

  const cleanTitle = report.target.replace(/[^a-zA-Z0-9]/g, '-').replace(/-+/g, '-').toLowerCase();
  doc.save(`security-report-${cleanTitle}.pdf`);
}
