'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { Shield, Play, Check, X, AlertTriangle, Globe, FileDown } from 'lucide-react';
import { useReportsStore } from '@/lib/store';
import { exportAuditToPDF } from '@/lib/utils/export';

function getErrorMessage(error: unknown) {
  return error instanceof Error ? error.message : 'API connection failed. Please try again.';
}

interface ApiErrorPayload {
  errorCode?: string;
  message?: string;
  details?: string;
  retryable?: boolean;
  error?: string;
}

interface AuditCheck {
  name: string;
  status: 'pending' | 'running' | 'pass' | 'warn' | 'fail' | 'error';
  message: string;
  details?: string;
}

export default function AuditPage() {
  const [url, setUrl] = useState('');
  const [running, setRunning] = useState(false);
  const [checks, setChecks] = useState<AuditCheck[]>([]);
  const [score, setScore] = useState<number | null>(null);
  const [grade, setGrade] = useState<string>('');
  const [errorMsg, setErrorMsg] = useState('');
  const [errorCode, setErrorCode] = useState('');
  const [errorRetryable, setErrorRetryable] = useState(false);
  const [auditReport, setAuditReport] = useState('');
  const { addReport } = useReportsStore();


  const auditCheckList = [
    'URL Validation',
    'HTTPS Check',
    'SSL/TLS Certificate',
    'Content Security Policy (CSP)',
    'HSTS Check',
    'X-Frame-Options',
    'X-Content-Type-Options',
    'Referrer Policy',
    'CORS Policy Check',
    'Cookie Security Check',
    'robots.txt presence',
  ];


  const runAudit = async () => {
    if (!url.trim()) return;
    setErrorMsg('');
    setErrorCode('');
    setErrorRetryable(false);
    setScore(null);
    setGrade('');
    setChecks([]);

    let targetUrl = url.trim();
    if (!targetUrl.startsWith('http://') && !targetUrl.startsWith('https://')) {
      targetUrl = 'https://' + targetUrl;
    }

    setRunning(true);

    // Initialize UI checks to pending
    const initialChecks: AuditCheck[] = auditCheckList.map((name) => ({
      name,
      status: 'pending',
      message: 'Queueing analysis...',
    }));
    setChecks(initialChecks);

    const controller = new AbortController();
    const timeoutId = window.setTimeout(() => controller.abort(), 12_000);

    try {
      // 1. Fire real parallel audits on Next.js backend
      const response = await fetch('/api/audit', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ url: targetUrl }),
        signal: controller.signal,
      });

      const resData = (await response.json()) as ApiErrorPayload & {
        success?: boolean;
        checks?: AuditCheck[];
        score?: number;
        grade?: string;
        url?: string;
        hostname?: string;
      };

      if (!response.ok || !resData.success) {
        setErrorCode(resData.errorCode || `HTTP_${response.status}`);
        setErrorRetryable(resData.retryable ?? (response.status >= 500 || response.status === 429));
        throw new Error(resData.message || resData.error || 'Security audit request failed');
      }

      const realChecks: AuditCheck[] = resData.checks || [];

      // 2. Play satisfying UI sequential reveal animation for premium UX
      const activeChecks = [...initialChecks];
      for (let i = 0; i < auditCheckList.length; i++) {
        // Mark current running
        activeChecks[i] = {
          ...activeChecks[i],
          status: 'running',
          message: 'Resolving parameters...',
        };
        setChecks([...activeChecks]);

        // Small delay to simulate scanning step
        await new Promise((r) => setTimeout(r, 250));

        // Find the matched result from API response
        const matchedReal = realChecks.find((rc) => rc.name === auditCheckList[i]);
        if (matchedReal) {
          activeChecks[i] = matchedReal;
        } else {
          activeChecks[i] = {
            name: auditCheckList[i],
            status: 'warn',
            message: 'Metric absent',
            details: 'Could not obtain security metric detail.',
          };
        }
        setChecks([...activeChecks]);
      }

      setScore(resData.score ?? 0);
      setGrade(resData.grade || 'F');

      // 3. Compile high-quality, professional Markdown Report
      const passedCount = realChecks.filter((c) => c.status === 'pass').length;
      const warnCount = realChecks.filter((c) => c.status === 'warn').length;
      const failedCount = realChecks.filter((c) => c.status === 'fail' || c.status === 'error').length;

      const reportContent = `# Website Security Audit Report

**Audit Target:** ${resData.url || targetUrl}
**Scan Timestamp:** ${new Date().toUTCString()}
**Overall Security Score:** ${resData.score ?? 0}/100 (Grade ${resData.grade || 'F'})

---

## Executive Summary
This professional vulnerability audit was generated by CyberKit Security. The scan evaluated active server protocols, TLS properties, and HTTP response headers to gauge exposure to XSS, Clickjacking, and Session Hijacking.

* **Passed Verifications**: ${passedCount}
* **Warnings / Recommendations**: ${warnCount}
* **Vulnerabilities / Failures**: ${failedCount}

---

## Detailed Security Findings

${realChecks
  .map(
    (c) => `### [${c.status.toUpperCase()}] ${c.name}
* **Status**: ${c.status === 'pass' ? 'SAFE' : c.status === 'fail' ? 'FAIL' : 'WARNING'}
* **Details**: ${c.message}
${c.details ? `* **Technical context**: *${c.details}*` : ''}
`
  )
  .join('\n')}

---
*Disclaimer: This report was compiled by automated checks. Implement parameters carefully in staging before pushing changes to production.*`;

      // Save report to Zustand Reports Store (persisted to localStorage)
      addReport({
        title: `Audit: ${resData.hostname || targetUrl}`,
        target: targetUrl,
        content: reportContent,
        format: 'markdown',
        toolsUsed: auditCheckList,
      });

      setAuditReport(reportContent);


    } catch (err: unknown) {
      if (err instanceof DOMException && err.name === 'AbortError') {
        setErrorCode('CLIENT_TIMEOUT');
        setErrorRetryable(true);
        setErrorMsg('Audit request timed out after 12 seconds.');
      } else {
        setErrorMsg(getErrorMessage(err));
      }
      setChecks((current) =>
        current.length
          ? current.map((check) =>
              check.status === 'pending' || check.status === 'running'
                ? {
                    ...check,
                    status: 'error',
                    message: 'Audit step did not complete.',
                    details: 'Retry the audit or verify that the target is reachable.',
                  }
                : check
            )
          : []
      );
    } finally {
      window.clearTimeout(timeoutId);
      setRunning(false);
    }
  };

  const statusIcon = (status: AuditCheck['status']) => {
    switch (status) {
      case 'pass':
        return <Check size={16} className="text-emerald-400" />;
      case 'fail':
        return <X size={16} className="text-rose-500" />;
      case 'warn':
        return <AlertTriangle size={16} className="text-amber-500" />;
      case 'running':
        return (
          <div className="w-4 h-4 border-2 border-cyan-400 border-t-transparent rounded-full animate-spin" />
        );
      default:
        return <div className="w-3.5 h-3.5 rounded-full bg-zinc-700" />;
    }
  };

  return (
    <div className="p-4 md:p-8 max-w-4xl mx-auto space-y-6">
      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}>
        <h1 className="text-3xl font-bold flex items-center gap-3">
          <Shield size={32} className="text-cyan-400 drop-shadow-[0_0_8px_rgba(34,211,238,0.5)]" /> 
          Website Security Audit
        </h1>
        <p className="text-sm text-zinc-400 mt-1">
          Perform a real-time cybersecurity diagnostic audit on any domain or URL to evaluate security headers and SSL status.
        </p>
      </motion.div>

      {/* URL Input Form */}
      <div className="bg-zinc-900/50 backdrop-blur-md border border-zinc-800 rounded-xl p-6 shadow-xl">
        <div className="flex flex-col sm:flex-row gap-4">
          <div className="relative flex-1">
            <Globe size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-500" />
            <input
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              placeholder="e.g. google.com or https://github.com"
              className="w-full bg-zinc-950 border border-zinc-800 rounded-lg pl-12 pr-4 py-3 text-sm text-zinc-200 placeholder-zinc-500 focus:outline-none focus:border-cyan-400 focus:ring-1 focus:ring-cyan-400 transition-all"
              onKeyDown={(e) => e.key === 'Enter' && runAudit()}
              disabled={running}
            />
          </div>
          <button
            onClick={runAudit}
            disabled={running || !url.trim()}
            className="bg-cyan-500 hover:bg-cyan-400 text-black font-semibold rounded-lg px-6 py-3 text-sm flex items-center justify-center gap-2 transition-all disabled:opacity-50 disabled:cursor-not-allowed hover:shadow-[0_0_15px_rgba(6,182,212,0.4)]"
          >
            {running ? (
              <>
                <span className="w-4 h-4 border-2 border-black border-t-transparent rounded-full animate-spin" />
                Auditing...
              </>
            ) : (
              <>
                <Play size={16} fill="currentColor" />
                Start Security Audit
              </>
            )}
          </button>
        </div>

        {errorMsg && (
          <div className="mt-4 p-3 bg-rose-500/10 border border-rose-500/20 text-rose-400 text-xs rounded-lg flex flex-col sm:flex-row sm:items-center gap-3 justify-between">
            <div>
              <div className="font-semibold">{errorMsg}</div>
              {errorCode && <div className="text-[10px] font-mono text-rose-300/80 mt-1">{errorCode}</div>}
            </div>
            {errorRetryable && (
              <button
                onClick={runAudit}
                disabled={running}
                className="btn-cyber btn-danger btn-sm self-start sm:self-center"
              >
                Retry
              </button>
            )}
          </div>
        )}
      </div>

      {/* Audit Score Output */}
      {score !== null && (
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="bg-zinc-900/50 backdrop-blur-md border border-zinc-800 rounded-xl p-6 flex flex-col md:flex-row items-center justify-around gap-6 shadow-xl"
        >
          <div className="text-center md:text-left space-y-2">
            <h2 className="text-lg font-semibold text-zinc-200">Security Score Summary</h2>
            <p className="text-xs text-zinc-400 max-w-sm">
              Audit results indicate key security attributes are active. Review failures and warnings below to strengthen protection against exploits.
            </p>
            <div className="flex gap-4 text-xs font-mono pt-2">
              <span className="text-emerald-400">{checks.filter((c) => c.status === 'pass').length} Passed</span>
              <span className="text-amber-400">{checks.filter((c) => c.status === 'warn').length} Warnings</span>
              <span className="text-rose-500">{checks.filter((c) => c.status === 'fail' || c.status === 'error').length} Failed</span>
            </div>
            
            <div className="pt-3 flex justify-center md:justify-start">
              <button
                onClick={() => {
                  let targetUrl = url.trim();
                  if (!targetUrl.startsWith('http://') && !targetUrl.startsWith('https://')) {
                    targetUrl = 'https://' + targetUrl;
                  }
                  try {
                    const host = new URL(targetUrl).hostname;
                    exportAuditToPDF(`Audit: ${host}`, targetUrl, auditReport);
                  } catch {
                    exportAuditToPDF(`Audit: ${targetUrl}`, targetUrl, auditReport);
                  }
                }}
                className="bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-400 border border-cyan-500/30 font-semibold rounded-lg px-4 py-2 text-xs flex items-center gap-2 transition-all hover:shadow-[0_0_10px_rgba(6,182,212,0.2)]"
              >
                <FileDown size={14} /> Export PDF Report
              </button>
            </div>
          </div>


          <div className="flex items-center gap-6">
            <div className="relative flex items-center justify-center">
              {/* Outer Score Circle */}
              <svg className="w-24 h-24 transform -rotate-90">
                <circle cx="48" cy="48" r="40" className="stroke-zinc-800 fill-none" strokeWidth="6" />
                <circle
                  cx="48"
                  cy="48"
                  r="40"
                  className={`fill-none transition-all duration-1000 ${
                    grade === 'A' || grade === 'B'
                      ? 'stroke-emerald-400'
                      : grade === 'C'
                      ? 'stroke-amber-400'
                      : 'stroke-rose-500'
                  }`}
                  strokeWidth="6"
                  strokeDasharray="251.2"
                  strokeDashoffset={251.2 - (251.2 * score) / 100}
                />
              </svg>
              <div className="absolute flex flex-col items-center">
                <span className="text-2xl font-bold text-zinc-100">{score}</span>
                <span className="text-[10px] text-zinc-500 font-mono">SCORE</span>
              </div>
            </div>

            <div className="text-center">
              <div
                className={`w-16 h-16 rounded-full flex items-center justify-center text-3xl font-extrabold font-mono border-2 shadow-lg ${
                  grade === 'A'
                    ? 'bg-emerald-500/10 border-emerald-400 text-emerald-400 shadow-emerald-500/20'
                    : grade === 'B'
                    ? 'bg-emerald-600/10 border-emerald-500 text-emerald-500 shadow-emerald-600/10'
                    : grade === 'C'
                    ? 'bg-amber-500/10 border-amber-400 text-amber-400 shadow-amber-500/20'
                    : 'bg-rose-500/10 border-rose-500 text-rose-500 shadow-rose-500/20'
                }`}
              >
                {grade}
              </div>
              <span className="text-[10px] text-zinc-500 font-mono mt-1 block">GRADE</span>
            </div>
          </div>
        </motion.div>
      )}

      {/* Diagnostic Check Results List */}
      {checks.length > 0 && (
        <div className="bg-zinc-900/50 backdrop-blur-md border border-zinc-800 rounded-xl overflow-hidden shadow-xl divide-y divide-zinc-800">
          <div className="bg-zinc-950 px-6 py-4 flex items-center justify-between border-b border-zinc-800">
            <span className="text-xs font-semibold uppercase tracking-wider text-zinc-400">Diagnostic Checklist</span>
            <span className="text-xs text-zinc-500 font-mono">
              {checks.filter((c) => c.status !== 'pending' && c.status !== 'running').length} / {checks.length} complete
            </span>
          </div>

          {checks.map((check, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: i * 0.05 }}
              className={`flex items-start gap-4 px-6 py-4 hover:bg-zinc-950/30 transition-colors ${
                check.status === 'pending' || check.status === 'running' ? 'animate-pulse' : ''
              }`}
            >
              <div className="mt-1 flex-shrink-0">{statusIcon(check.status)}</div>
              
              <div className="flex-1 min-w-0">
                <div className="flex items-center justify-between gap-2">
                  <span className="text-sm font-semibold text-zinc-200">{check.name}</span>
                  <span
                    className={`text-[10px] font-mono uppercase px-2 py-0.5 rounded border ${
                      check.status === 'pass'
                        ? 'bg-emerald-500/5 border-emerald-500/20 text-emerald-400'
                        : check.status === 'fail'
                        ? 'bg-rose-500/5 border-rose-500/20 text-rose-400'
                        : check.status === 'warn'
                        ? 'bg-amber-500/5 border-amber-500/20 text-amber-400'
                        : check.status === 'running'
                        ? 'bg-cyan-500/5 border-cyan-500/20 text-cyan-400'
                        : 'bg-zinc-800/30 border-zinc-700 text-zinc-400'
                    }`}
                  >
                    {check.status}
                  </span>
                </div>
                <p className="text-xs text-zinc-400 mt-0.5">{check.message}</p>
                {check.details && (
                  <p className="text-[11px] font-mono text-zinc-500 mt-1 pl-2 border-l border-zinc-800">
                    {check.details}
                  </p>
                )}
              </div>
            </motion.div>
          ))}
        </div>
      )}
    </div>
  );
}
